In [1]:
# 导入所有可能用到的库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
import warnings
import pulp
# 根据需要导入其他库

# 全局美化设置
plt.rcParams['font.sans-serif'] = ['SimHei']  # 解决中文显示问题
plt.rcParams['axes.unicode_minus'] = False     # 解决负号显示问题
sns.set_style('whitegrid')                     # 设置绘图风格
warnings.filterwarnings("ignore", category=UserWarning)

print("□ 指挥中心已启动，所有库准备就绪!(警告过滤器已开启)")

□ 指挥中心已启动，所有库准备就绪!(警告过滤器已开启)

In [5]:
# ----------------- 请在这里修改您的文件名 -----------------
file_path_1 = r'E:\我的大学四年\大一下\数模\23年华数杯C题\附件.xlsx'
#file_path_2 = '文件2.csv'
# file_path_3 = '...' # 如果有更多文件，在此处添加
# --------------------------------------------------------

try:
    # 尝试用Pandas读取数据，您的主要竞赛库是pd.read_excel()和pd.read_csv()
    df1 = pd.read_excel(file_path_1)
    #df2 = pd.read_csv(file_path_2, encoding='gbk') # CSV文件有时需要指定编码，如gbk
    # df3 = ...
    print(f"✔️ 所有附件数据加载成功！")
    
    print("\n[--df1数据预览 (前5行)--]")
    display(df1.head())
    #print("\n[--df2数据预览 (前5行)--]")
    #display(df2.head())
    
except FileNotFoundError as e:
    print(f"❌ 文件未找到，请仔细检查文件名和路径是否完全正确: {e}")
except Exception as e:
    print(f"❌ 数据加载失败，可能是编码问题或其他错误: {e}")

✔️ 所有附件数据加载成功！

[--df1数据预览 (前5行)--]

,编号,母亲年龄,婚姻状况,教育程度,妊娠时间（周数）,分娩方式,CBTS,EPDS,HADS,婴儿行为特征,...,整晚睡眠时间（时：分：秒）,睡醒次数,入睡方式,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,1.0,34.0,已婚,研究生,37.0,自然分娩,3.0,13.0,9.0,中等型,...,10:00:00,3.0,抚触法,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,33.0,已婚,研究生,42.0,自然分娩,0.0,0.0,3.0,安静型,...,11:00:00,0.0,环境营造法,NaN,补充说明（数值含义）,NaN,NaN,NaN,NaN,NaN
2,3.0,37.0,已婚,研究生,41.0,自然分娩,4.0,8.0,9.0,安静型,...,12:00:00,1.0,抚触法,NaN,数值,婚姻状况,教育程度,分娩方式,婴儿性别,入睡方式
3,4.0,31.0,已婚,研究生,37.5,自然分娩,6.0,16.0,13.0,安静型,...,11:00:00,2.0,哄睡法,NaN,1,未婚,小学,自然分娩,男性,哄睡法：通过轻声哄唤、摇晃、拍打等方式，使婴儿感到安全和舒适，进而入睡。
4,5.0,36.0,未婚,研究生,40.0,自然分娩,1.0,3.0,3.0,中等型,...,10:30:00,1.0,环境营造法,NaN,2,已婚,初中,剖宫产,女性,抚触法：通过轻柔的按摩、揉捏等方式，促进婴儿的放松和入睡。

In [9]:
# --------------------------------------------------------------------------------------------------------------------------------
# [-- 2.1 检查df1整体信息 --]
# --------------------------------------------------------------------------------------------------------------------------------
print(f"[-- df1 数据整体概览 (info) --]")
df1.info()
print(f"**" * 40 + "\n")

print(f"[-- df1 数值型数据统计概览 (describe) --]")
display(df1.describe())
print(f"**" * 40 + "\n")

print(f"[-- df1 非数值型数据统计概览 (describe for objects) --]")
display(df1.describe(include='object'))
print(f"**" * 40 + "\n")

[-- df1 数据整体概览 (info) --]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   编号             401 non-null    float64
 1   母亲年龄           401 non-null    float64
 2   婚姻状况           443 non-null    object
 3   教育程度           401 non-null    object
 4   妊娠时间（周数）       401 non-null    float64
 5   分娩方式           401 non-null    object
 6   CBTS           401 non-null    float64
 7   EPDS           401 non-null    float64
 8   HADS           401 non-null    float64
 9   婴儿行为特征         381 non-null    object
 10  婴儿性别           401 non-null    object
 11  婴儿年龄（月）        401 non-null    float64
 12  整晚睡眠时间（时：分：秒）  381 non-null    object
 13  睡醒次数           381 non-null    float64
 14  入睡方式           381 non-null    object
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    16 non-null     object
 17  Unnamed: 17    7 non-null      object
 18  Unnamed: 18    6 non-null      object
 19  Unnamed: 19    3 non-null      object
 20  Unnamed: 20    3 non-null      object
 21  Unnamed: 21    6 non-null      object
dtypes: float64(9), object(13)
memory usage: 76.3+ KB
********************************************************************************

[-- df1 数值型数据统计概览 (describe) --]

,编号,母亲年龄,妊娠时间（周数）,CBTS,EPDS,HADS,婴儿年龄（月）,睡醒次数,Unnamed: 15
count,401.000000,401.000000,401.000000,401.000000,401.000000,401.000000,401.000000,381.000000,0.0
mean,205.201995,30.154613,39.142394,5.965087,9.082294,7.865337,1.952618,1.467192,NaN
std,118.814989,4.363603,1.885404,4.975819,6.716823,4.275725,0.821736,1.621273,NaN
min,1.000000,19.000000,26.500000,0.000000,0.000000,0.000000,1.000000,0.000000,NaN
25%,103.000000,27.000000,38.000000,2.000000,4.000000,5.000000,1.000000,0.000000,NaN
50%,205.000000,30.000000,39.200000,5.000000,8.000000,7.000000,2.000000,1.000000,NaN
75%,309.000000,33.000000,40.400000,9.000000,13.000000,11.000000,3.000000,2.000000,NaN
max,410.000000,47.000000,43.000000,21.000000,28.000000,20.000000,3.000000,10.000000,NaN

********************************************************************************

[-- df1 非数值型数据统计概览 (describe for objects) --]

,婚姻状况,教育程度,分娩方式,婴儿行为特征,婴儿性别,整晚睡眠时间（时：分：秒）,入睡方式,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
count,443,401,401,381,401,381,381,16,7,6,3,3,6
unique,2,5,2,3,2,15,5,16,7,6,3,3,6
top,已婚,研究生,自然分娩,中等型,男性,10:00:00,环境营造法,补充说明（数值含义）,婚姻状况,教育程度,分娩方式,婴儿性别,入睡方式
freq,429,187,396,221,207,107,164,1,1,1,1,1,1

********************************************************************************

In [14]:
import pandas as pd
import numpy as np
import re

df_cleaned = df1.copy()

print("--- 开始数据清洗 ---")

# 步骤 1：处理多余行和列
# 从 info() 结果看，最后几行是补充说明，而非数据，需要删除。
# 另外，Unnamed 系列列几乎为空，也需要删除。
df_cleaned = df_cleaned.iloc[0:401, :]
df_cleaned = df_cleaned.drop(columns=['Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21'])
print("⚫ 步骤 1: 已删除多余行和列。")
print(f"⚫ 剩余数据量: {df_cleaned.shape}")

# 步骤 2: 处理列名不规范
# 移除列名中的特殊字符和多余空格，便于后续操作。
df_cleaned.columns = df_cleaned.columns.str.replace('（时：分：秒）', '', regex=False).str.replace('...', '', regex=False).str.strip()
print("⚫ 步骤 2: 列名已清洗。")
print(f"⚫ 新列名: {df_cleaned.columns.tolist()}")

# 步骤 3: 处理时间数据格式
# 使用自定义函数处理不规范的时间字符串，将其转换为pd.to_timedelta可接受的格式。
def parse_time_string(time_str):
    if pd.isna(time_str):
        return np.nan
    time_str = str(time_str).strip()
    match = re.match(r'(\d+):(\d+):(\d+)', time_str)
    if match:
        return time_str
    else:
        # 如果不是标准格式，尝试补全为标准格式，例如 '10' -> '10:00:00'
        parts = time_str.split(':')
        if len(parts) == 1 and parts[0].isdigit():
            return f"{int(parts[0]):02d}:00:00"
        elif len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
            return f"{int(parts[0]):02d}:{int(parts[1]):02d}:00"
    return time_str

df_cleaned['整晚睡眠时间'] = df_cleaned['整晚睡眠时间'].astype(str).apply(parse_time_string)
df_cleaned['整晚睡眠时间'] = pd.to_timedelta(df_cleaned['整晚睡眠时间'])
print("⚫ 步骤 3: 已将'整晚睡眠时间'列转换为时间格式。")

# 步骤 4: 处理缺失值
# 考虑到数据量较少，对不同列采用不同的缺失值填充策略。
# 采用中位数对数值型数据进行填充，众数对分类数据进行填充。
numeric_cols = df_cleaned.select_dtypes(include='float64').columns
for col in numeric_cols:
    median_val = df_cleaned[col].median()
    df_cleaned[col].fillna(median_val, inplace=True)

categorical_cols = df_cleaned.select_dtypes(include='object').columns
for col in categorical_cols:
    mode_val = df_cleaned[col].mode()[0]
    df_cleaned[col].fillna(mode_val, inplace=True)

print("⚫ 步骤 4: 缺失值已处理。")
print("⚫ 缺失值处理后，各列非空值数量：")
df_cleaned.info()


print("\n--- 数据清洗结束 ---")
print("✔️ 已成功根据你的【侦察笔记】清洗数据！")

--- 开始数据清洗 ---
⚫ 步骤 1: 已删除多余行和列。
⚫ 剩余数据量: (401, 15)
⚫ 步骤 2: 列名已清洗。
⚫ 新列名: ['编号', '母亲年龄', '婚姻状况', '教育程度', '妊娠时间（周数）', '分娩方式', 'CBTS', 'EPDS', 'HADS', '婴儿行为特征', '婴儿性别', '婴儿年龄（月）', '整晚睡眠时间', '睡醒次数', '入睡方式']
⚫ 步骤 3: 已将'整晚睡眠时间'列转换为时间格式。
⚫ 步骤 4: 缺失值已处理。
⚫ 缺失值处理后，各列非空值数量：
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   编号        401 non-null    float64
 1   母亲年龄      401 non-null    float64
 2   婚姻状况      401 non-null    object
 3   教育程度      401 non-null    object
 4   妊娠时间（周数）  401 non-null    float64
 5   分娩方式      401 non-null    object
 6   CBTS      401 non-null    float64
 7   EPDS      401 non-null    float64
 8   HADS      401 non-null    float64
 9   婴儿行为特征    401 non-null    object
 10  婴儿性别      401 non-null    object
 11  婴儿年龄（月）   401 non-null    float64
 12  整晚睡眠时间    381 non-null    timedelta64[ns]
 13  睡醒次数      401 non-null    float64
 14  入睡方式      401 non-null    object
dtypes: float64(8), object(6), timedelta64[ns](1)
memory usage: 47.1+ KB

--- 数据清洗结束 ---
✔️ 已成功根据你的【侦察笔记】清洗数据！

C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_val, inplace=True)
C:\Users\crj\AppData\Local\Temp\ipykernel_25692\4118045121.py:56: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(mode_val, inplace=True)